apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-curl-pld-server
  namespace: nginx-curl-pld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-curl-pld-server
  template:
    metadata:
      labels:
        app: nginx-curl-pld-server
    spec:
      containers:
        - name: nginx-curl-pld-server
          image: nginx:latest
          volumeMounts:
            - name: nginx-curl-pld-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: nginx-curl-pld-config
          configMap:
            name: nginx-curl-pld-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-curl-pld-config
  namespace: nginx-curl-pld
data:
  default.conf: |
    server {
        listen 80;
        server_name _;

        client_max_body_size 200m;

        location / {
            # Allow all methods including POST
            limit_except GET POST {
                deny all;
            }

            return 200 "OK\n";
            add_header Content-Type text/plain;
        }
    }
