apiVersion: v1
kind: Service
metadata:
    name: nginx-server
    namespace: nginx-wrk
spec:
    selector:
        app: nginx
    ports:
        - protocol: TCP
          port: 80
          targetPort: 80
    type: LoadBalancer
