apiVersion: batch/v1
kind: Job
metadata:
  name: iperf-client
  namespace: iperf
spec:
  template:
    metadata:
      labels:
        app: iperf-client
    spec:
      containers:
        - name: iperf-client
          image: networkstatic/iperf3
          command:
            - "/bin/sh"
            - "-c"
            - >
              sleep 10;
              iperf3 -c ${SERVER_ADDRESS} -J -t ${BENCHMARKS_N}
      restartPolicy: Never
  backoffLimit: 4
