apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: cluster-2
nodes:
  - role: control-plane
  - role: worker
networking:
  disableDefaultCNI: true
  podSubnet: "10.2.0.0/16"
  serviceSubnet: "10.20.0.0/16"
  apiServerPort: 6442
