---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
    name: docker-kind-network-pool
    namespace: metallb-system
spec:
    addresses:
        - 172.18.0.176-172.18.0.200
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
    name: docker-kind-network-advertisement
    namespace: metallb-system
