---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: node-ip-address-pool
  namespace: metallb-system
spec:
  addresses:
    - ${NODE_IP_ADDR}-${NODE_IP_ADDR}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: node-ip-address-pool
  namespace: metallb-system
