apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: cluster-1
nodes:
  - role: control-plane
networking:
  ipFamily: ipv6
  disableDefaultCNI: true
  podSubnet: "fd00:10:1::/64"
  serviceSubnet: "fd00:10:10::/112"
  apiServerAddress: 127.0.0.1
  apiServerPort: 6441
