apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: cluster-2
nodes:
  - role: control-plane
networking:
  ipFamily: ipv6
  disableDefaultCNI: true
  podSubnet: "fd00:10:2::/64"
  serviceSubnet: "fd00:10:20::/112"
  apiServerAddress: 127.0.0.1
  apiServerPort: 6442
