- name: Install git and yq on the host
  become: true
  package:
    name:
      - git
      - yq
    state: present

- name: Clone multi-cluster-benchmarking repository into home directory
  git:
    repo: https://github.com/benedictweis/multi-cluster-benchmarking
    dest: "{{ ansible_env.HOME }}/multi-cluster-benchmarking"
    clone: true
    update: true
    force: true

- name: Copy kubeconfig_instance_1.yaml to cloned repo
  copy:
    src: ./kubeconfig_instance_1.yaml
    dest: "{{ ansible_env.HOME }}/multi-cluster-benchmarking/kubeconfig_instance_1.yaml"

- name: Copy kubeconfig_instance_2.yaml to cloned repo
  copy:
    src: ./kubeconfig_instance_2.yaml
    dest: "{{ ansible_env.HOME }}/multi-cluster-benchmarking/kubeconfig_instance_2.yaml"

- name: Run the finish-setup.sh script
  shell: |
    cd "{{ ansible_env.HOME }}/multi-cluster-benchmarking/providers/k3s"
    chmod +x finish-setup.sh
    ./finish-setup.sh
  args:
    executable: /bin/bash
