- name: Update apt cache
  become: true
  apt:
    update_cache: yes

- name: Install git on the host
  become: true
  package:
    name:
      - git
    state: present

- name: Download yq binary
  become: true
  get_url:
    url: https://github.com/mikefarah/yq/releases/latest/download/yq_linux_arm64
    dest: /usr/local/bin/yq
    mode: "0755"

- name: Clone multi-cluster-benchmarking repository into home directory
  git:
    repo: https://github.com/benedictweis/multi-cluster-benchmarking
    dest: "{{ ansible_env.HOME }}/multi-cluster-benchmarking"
    clone: true
    update: true
    force: true

- name: Copy kubeconfig_instance_1.yaml to cloned repo
  copy:
    src: ./kubeconfig_instance_1.yaml
    dest: "{{ ansible_env.HOME }}/multi-cluster-benchmarking/kubeconfig_instance_1.yaml"

- name: Copy kubeconfig_instance_2.yaml to cloned repo
  copy:
    src: ./kubeconfig_instance_2.yaml
    dest: "{{ ansible_env.HOME }}/multi-cluster-benchmarking/kubeconfig_instance_2.yaml"

- name: Run the finish-setup.sh script
  shell: |
    cd "{{ ansible_env.HOME }}/multi-cluster-benchmarking/providers/k3s"
    chmod +x finish-setup.sh
    ./finish-setup.sh
  args:
    executable: /bin/bash
