apiVersion: v1
kind: Service
metadata:
    name: iperf-server
    namespace: iperf
spec:
    selector:
        app: iperf-server
    ports:
        - protocol: TCP
          port: 5201
          targetPort: 5201
    type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: iperf-config
    namespace: iperf
data:
    SERVER_ADDRESS: "iperf-server"
    INITIAL_SLEEP: "10"
