apiVersion: v1
kind: Service
metadata:
    name: nginx-server
    namespace: nginx-curl
    labels:
        app: nginx-server
        service: nginx-server
spec:
    selector:
        app: nginx
    ports:
        - protocol: TCP
          port: 80
          targetPort: 80
    type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: nginx-config
    namespace: nginx-curl
data:
    SERVER_ADDRESS: "nginx-server"
    SERVER_PORT: "80"
    INITIAL_SLEEP: "10"
