apiVersion: v1
kind: Service
metadata:
    name: iperf-server
    namespace: iperf
    labels:
        mirror.linkerd.io/exported: "true"
spec:
    selector:
        app: iperf-server
    ports:
        - protocol: TCP
          port: 5201
          targetPort: 5201
    type: ClusterIP
