apiVersion: batch/v1
kind: Job
metadata:
  name: grpcbin-grpcurl-client
  namespace: grpcbin-grpcurl
spec:
  template:
    metadata:
      labels:
        app: grpcbin-grpcurl-client
    spec:
      containers:
        - name: grpcbin-grpcurl-client
          image: fullstorydev/grpcurl:latest-alpine
          command:
            - "/bin/sh"
            - "-c"
            - >

              sleep 10;
              for i in ${DOLLAR}(seq 1 ${BENCHMARKS_N}); do
                ts=${DOLLAR}(date +%s%N);
                grpcurl -plaintext ${SERVER_ADDRESS}:9000 hello.HelloService/SayHello;
                ts_end=${DOLLAR}(date +%s%N);
                echo ${DOLLAR}(( (ts_end - ts) / 1000000 ));          
                done
      restartPolicy: Never
