apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpcbin-grpcurl-server
  namespace: grpcbin-grpcurl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpcbin-grpcurl-server
  template:
    metadata:
      labels:
        app: grpcbin-grpcurl-server
    spec:
      containers:
        - name: grpcbin-grpcurl-server
          image: kong/grpcbin
          ports:
            - containerPort: 9000
